name: Check PR title format

on:
  pull_request:
    branches: [main] 
    types: [opened, edited, synchronize, reopened]

jobs:
  validate-title:
    name: Check PR title format ✅  

    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title starts with `feat:`, `fix:`, etc.
        run: |
          echo "Checking title: '${{ github.event.pull_request.title }}'"
          echo "${{ github.event.pull_request.title }}" | grep -E '^(?:\[[A-Z]{2,3}-[0-9]+\] )?(feat|fix|chore|docs|style|refactor|test|perf): .+' || {
            echo "❌ ERROR: PR title must start with 'feat:', 'fix:', etc."
            exit 1
          }
